{
  emacs,
  pkgs,
}:
emacs.pkgs.withPackages (
  epkgs: with epkgs; [
    adoc-mode
    aidermacs
    ansible
    auto-dark
    avy
    awk-ts-mode
    bitbake-ts-mode
    breadcrumb
    cape
    cmake-mode
    compile-multi
    compile-multi-embark
    compile-multi-nerd-icons
    consult
    consult-compile-multi
    consult-dash
    consult-eglot
    consult-eglot-embark
    consult-flyspell
    copilot
    corfu
    csv-mode
    dape
    dash-docs
    devicetree-ts-mode
    diff-hl
    diminish
    direnv
    docker-compose-mode
    dockerfile-mode
    drag-stuff
    dtrt-indent
    elisp-lint
    embark
    embark-consult
    expand-region
    git-commit-ts-mode
    gitlab-ci-mode
    gnuplot
    go-mode
    haskell-mode
    haskell-ts-mode
    helpful
    hl-todo
    jq-ts-mode
    just-ts-mode
    magit
    marginalia
    markdown-mode
    mermaid-mode
    mermaid-ts-mode
    modern-cpp-font-lock
    multiple-cursors
    nerd-icons
    nerd-icons-completion
    nerd-icons-corfu
    nerd-icons-dired
    nerd-icons-ibuffer
    nix-mode
    nix-ts-mode
    orderless
    org-appear
    org-modern
    package-lint
    pretty-sha-path
    rainbow-delimiters
    sr-speedbar
    ssh-config-mode
    super-save
    terraform-mode
    tree-sitter-langs
    treesit-auto
    treesit-fold
    treesit-grammars.with-all-grammars
    vertico
    vterm
    vundo
    wgrep
    yaml-mode
    zoxide
  ]
)
