[
  ./config
  ./hardware/apple.nix
  ./hardware/mac-mini-2018.nix
  ./hardware/macbook-air.nix
  ./roles/desktop
  ./roles/developer
  ./roles/nix-companion-server.nix
  ./roles/server
  ./services/opensearch-dashboards
  ./services/rclone-sync
]
