name: Push to cachix

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: jylhis-nixos
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check
    - run: nix build .#emacs-markus
    - run: nix-shell --run "echo OK"
    - run: nix flake archive --json | jq -r '.path,(.inputs|to_entries[].value.path)' cachix push jylhis-nixos
