hello: ENC[AES256_GCM,data:GX7fKw5W4Bcf1ik29Eqzw+lu448OfH6sFBmyZsUaZLSlmVDj9+W54ENeOchW1w==,iv:EKRWwF7NM55ZOa88OSwyVdYCziFpaPil5QWaILREWiY=,tag:IYxTQ86MYCSD0xS1PgPB6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yaq7q9cpuws7uay7z0x2frxwpmjlngk0vvqcg4mk9fzcxt09uusq95wfju
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaWFYVFlGU2M0N3Q4T2Z2
            MmxTbGRSKzJqbDNVeUpCRmh1U2dlN20xN0ZRCk9DQ1B4U0YzR3hxQ29MWVdWQm5x
            M2VVcmFhZ2Q1YmJYZTJYa0NsWmxmSXcKLS0tIExwU2JrdytoalBLYnZCb3IvcURT
            a1ViT3N5aDdzV2pibE9jd3NJQzZzbEUK4hU1/Ympj5R2FcR+XfDnlNJdjCy3LpM+
            AMMiMcy2a8hXY0Xs3d1Iu9Y+aPAOV8ytVDvAXsB/VZcuZ0Ir1xMuPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age148qahuqr3269ytmlda7r28873vhk3xx80lmsj4awkhhqrggvp5zsag7xgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWE9ZVDE2SGVQUEQvejNw
            djRzYm1IQk02MTYySmpkVktWTFFnbXVQcVNJClJZSGVRVjFFZk9LemJOWTN6Nko0
            MVMvRzdlYkE1UjJScXpnTGF6YU55d2cKLS0tIE1FajErcUNaNVNoc2VyclZURVBE
            WlZHbUVGOXA4Y1Z3WlVmMHpaV0ZpcVUKQ2EWMKjp6JTB6CcqaZPOOAciIkfaBywb
            CSbrVtz0i9dgCpVhkmoiJCxljr2wcyDoTrdyxmuNVi9VpXzhAWjj3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-08T19:46:21Z"
    mac: ENC[AES256_GCM,data:knDYsYh/lG+rE1yIsCyqZYjYHdgdgbaP2Y7pbrQMGV/Cr2NbA9ZJzUuZUiLeQrpB4ycRAbCdv9fW4lhMxue8ZjIoXlTyGNenu14LY3ZZSDrmrELxBxBAoMHpt1zrINJKwf2k5ORaxaB9oBVhAo/qonnNM1SqZaCzWBoMJb2Cf5M=,iv:uiI3j9w6X1AHl84YqVxOIA92MZxXkf1Stq59PhqS0Wo=,tag:o+7XiB7DKwmFWJ7OkCp5fA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
