tailscale_auth_key: ENC[AES256_GCM,data:FD5po/mI5GxyQwekfYlzsRD4QpRMOfELRAmUaG5fpyCh8nO0XSpy42G3AiwslPzjXA5C4QxPH7CCzEih72w=,iv:UtP/SWjpH9FLLtfcIPO3x6NUO5Pl1oEqsJ6yHFoMlc0=,tag:AMPtnOuBGaXCSXxk+uUJeA==,type:str]
netdata_claim_token: ENC[AES256_GCM,data:D0gtg6CnIpis6xuHikMhFL71IxYBqzcgpELaXZ+O0AM8gxKi30qvZ5VW9YAl/hlJA71r4g4FIwmKOEk2E+eKov/BBy7/ZpnHAziVS1UzyZ87wcX8q0dweltkYvRMFQa/rhdnGKDiFcQyJ7f2UpD1uAqhRgHIIrHuBXk2TMAPj4kfQYP0+yDD,iv:JB+hLjFq9KHnBrcRWtnG6BFUu1Jt59/CHug1MPTqRK0=,tag:8sVIeUr22YcuBUP49NfnPQ==,type:str]
grafana_admin_password: ENC[AES256_GCM,data:eZ3DIyer7aKcJq1ybtA4EdXHOtSBvI8=,iv:eB8Gl1L47h0pNAUJyphQPukL5fxxWBJmqaXyYDJaAjk=,tag:mu/Vkra0Z/YOvx7qzIcCxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yaq7q9cpuws7uay7z0x2frxwpmjlngk0vvqcg4mk9fzcxt09uusq95wfju
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQnpBUTU5Ujh0UkRTTjJ6
            ZmJUalVsNDFvV0d1ZjlBdUVnZXdQTncwbTF3CjBoRzZlVm5pMmM2cUpyOVVXbkQ3
            bFZ1ckJzZi9MV0VLOWNIWndaQWVNdHMKLS0tIGxDV0dsR3k3MG1pZlZJeCtuZENZ
            ZUhMSEk1Y1BYVzhzN0llOFFiNVV2V2sKtryVO6x+CNoVZk0B57mkJ8CWE7wYunzU
            o5T32Wpkv8gXR3+6gjwy0SawtXODKCYK/KJJWZIHmKeDmAZxqNrIPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lql6xv47pqyyakfrpdnw772pjf9mzvp0uh5mctkfwr75lzdjs3xs9tc68n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMXhqdGtXY2NIdEN6eDIz
            RDdkMGQrdmNvUytQWmFUeW55S2hWRFhKWWhzCis2ZC9SOWFYWFBzQUdzWnh4TGtX
            WnZBYlNNbk5QQ3hkVkl3ZzVJd1J2QkkKLS0tIFJKOHJ3MUE2ck0rbkNjeFRhbmNR
            M3NybExoMkU5TzBMTVFZU1FLYlJDeGcKX/WXhidcph9bAQlusSAUXlFNI9ivROhN
            EQXmP+Cw5wO1XanrQfuqTFcHWcwCHRbd/xEgCefiL7kfM84HyhD2Gw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n70s2ssmssfd3x9wn4x39f7tuqvhnp7q6pluww54fq6swgq7au7s2d8gk6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdVhtaDBwakViZlhTUlls
            ZDBrY1RGVFk5emVWSUJMR3V2dEsrRituM24wCjFVT2F5Q2RWODBHU1FqSWMvTy9M
            UnVRZndKL2lYWkRwOHhCS1dpYXZjRVUKLS0tIEFxRjZoWDJQSWgxRU8vRFNWMXJm
            NTVtT0ZrQXBRUzZ4bDJ1aUFjaHZaOWcKf5J3u9ztSjoFtVnMwa9PD+yzcIl1yZgB
            OhGFVUQuJB6PbnRAfi71NxTUIZ/5DXPGlmqFW00QmT4b6ZRgGDve/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-16T12:15:14Z"
    mac: ENC[AES256_GCM,data:+HBJOqbEXMsXBEstJq9Ut2+XySIpXQocG5Nm3x0Ivp2Cq5IC+KB98G0YzMq57u/TCzM13hTrDTO399DZL0eILUBHlDZuT/Ap79wCgTqar3WxXJDWnqjwGooLISvYkl1737B9jPiDYYjTJr6veK22rYb7EoEYscPbT5s5YQaqLo0=,iv:idG4+4c06gFnOjhyoTpu649ckM7AjRh0HrJe4qZfwgI=,tag:cvlZeIbnAzOb10TeoBb0YQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
