tailscale_auth_key: ENC[AES256_GCM,data:FD5po/mI5GxyQwekfYlzsRD4QpRMOfELRAmUaG5fpyCh8nO0XSpy42G3AiwslPzjXA5C4QxPH7CCzEih72w=,iv:UtP/SWjpH9FLLtfcIPO3x6NUO5Pl1oEqsJ6yHFoMlc0=,tag:AMPtnOuBGaXCSXxk+uUJeA==,type:str]
netdata_claim_token: ENC[AES256_GCM,data:D0gtg6CnIpis6xuHikMhFL71IxYBqzcgpELaXZ+O0AM8gxKi30qvZ5VW9YAl/hlJA71r4g4FIwmKOEk2E+eKov/BBy7/ZpnHAziVS1UzyZ87wcX8q0dweltkYvRMFQa/rhdnGKDiFcQyJ7f2UpD1uAqhRgHIIrHuBXk2TMAPj4kfQYP0+yDD,iv:JB+hLjFq9KHnBrcRWtnG6BFUu1Jt59/CHug1MPTqRK0=,tag:8sVIeUr22YcuBUP49NfnPQ==,type:str]
grafana_admin_password: ENC[AES256_GCM,data:eZ3DIyer7aKcJq1ybtA4EdXHOtSBvI8=,iv:eB8Gl1L47h0pNAUJyphQPukL5fxxWBJmqaXyYDJaAjk=,tag:mu/Vkra0Z/YOvx7qzIcCxQ==,type:str]
bazarr_api_key: ENC[AES256_GCM,data:o07CygB7UBak6efn8kniBp5TFpLtGkGxv0R9DR41V2Y=,iv:rPOEprOI8SKEk2qjWlYdf4KR1nYxGiq+tr16ndQyJ9w=,tag:N0JgWaMp2swK/kMDlLwgew==,type:str]
prowlarr_api_key: ENC[AES256_GCM,data:cC4XD+3Cxzok9RgjnSLaPUmKqhgLV+ySeXGS/c0bqVI=,iv:WP/REYRc2LNtUJVfAmsoU8l2TmeuHwnubEvRBfQY72s=,tag:JZdtUdPXvS7O9DXwHd1BcQ==,type:str]
radarr_api_key: ENC[AES256_GCM,data:lclbLdmltoJub+CPFt/kF+GO+N8O66buwEn4bTvhuYs=,iv:TVv2arnzod+cNz0sTyHfcsMnyE+QVuO5ZB/XFhs1gjU=,tag:mFBiKWaAwq7mX9eKQGTAbw==,type:str]
readarr_api_key: ENC[AES256_GCM,data:yuH6JY+2ZHVXuUkbrz1LHc7AhqV8v6VVS+i7KSwDfQc=,iv:XrRNbkD93jYsjIjflgmWf1Xbe3JpjlByBNh5e0IIMfU=,tag:82fsyEU5oRHrr8WiDJs6lA==,type:str]
sonarr_api_key: ENC[AES256_GCM,data:zHAaj9/4TEu+z94P9wn7MFPW0gAljiSm89phZqVNWzA=,iv:dRpeNXiJXZke1Qn/VKF5qhcUbAWklYegS3PuXOElROc=,tag:2kkAMKnUiklzpS1c9LlpaQ==,type:str]
lidarr_api_key: ENC[AES256_GCM,data:jsfH6/j002iUsRJhB/NxYDZnqjbNLBrsFxlQhUe08/U=,iv:5g6gFCs6ohVuLDLDZCqDgBu0sC5/lxxFSA0EHFbOYXg=,tag:7Ss6IjuRCI5I00CmDMcZ6A==,type:str]
jwt: ENC[AES256_GCM,data:U5DAcHEbwqGyutFf+itiR1o32qjCC9SEgSLf8OWVpuAC/DOaKg/swr0KbOUFHf01tU2WjiIZY13EKxPbw0m/Eg==,iv:28swiwhaFrJeK6qtbaSE7vWY+67O65SwdlPCR5C3VO4=,tag:RXEmtyvPoWuHnjpBBBkl1g==,type:str]
firefly_app_key: ENC[AES256_GCM,data:B8XZzDXSEoDcu65m8MKXAuSCsvr7iG3aRAsPww2KKrQ+OVXcphz4u7W1hGDVgZgz9EFk,iv:N0iQRsnvFUhoml9CArukZOiuGtPIMNa+0JQKx+O6v5A=,tag:s8tC5oE9WJS27Z1Hu6Rcxw==,type:str]
firefly_importer: ENC[AES256_GCM,data:jKNDVkbMpAWRYsA96x/ePgaB0rTi4inBJ6PS0cmK+jcLdviG9nPC7Btwmj40qkPFCfR89nbm5Ym0rcmdWp4WcD3A0RG3gxWXz28NLg8HjFYmJHeOB4rXStqP9Y1p4Yiuwqpfr3E+YIFMEwBNWTHf1dUsQsCQnxQtf8WGeQNI2lZIJClVjchEwlmF4QucLnENp0wN/HME6NdtZJis5imBN2Ro2Hczf5cGCYWI3GaYeNfJNN6UZ8R+jfXyGO7KGfYeFzeo9xzOU2pOUIGc8rVIahU/rdYJGIHvbp6GRAo2C+RRVKBho692kXQv0yX2j/szbmtRAA1OlnWva2b6aPjPP8XHYVTMwOgcq3yliEObZLUOlG9i7UpBU3XWnVMuIqTKzMqOGkhHnnMH+KO0yxtOTtuaYsog1k5m6Zgm35rl+VseaPfNj3G6ppFFWA2BlwcO1DiofVS4BIZmoqzdjYDRv9iqHQLirTxVA1Gc3qypwa5DhKhMIxdz7df+Gv/S618azVlWdI6TVKtEYjvFHQWsYSn2ZqVZetH8U3ot96Nt+CCrqSTigamjNlw2vo8PWSaMgJ6IXodqiWFBWSOP1SLGD4CJwSDFVkVRGG4UgHMvCj25+flUalBzFzpBqXvUU26yjqZShUN4+0t6WLYRm1IskAV4ySbd3hDQ3ZOSQdhqj/E7ZOoblpXpwAnoGzxwCl8wfJJNne326XAsf5oPugZriOFCGpSBpS4zPjZNr0NpcZBdfKPLwPmEpc3zzS4Cn+iDxUVdy+Zx4VbJUUYAqQKdonX0WiGonMF9yxh3YzvHqernMaTq9HRtKqswiD4CI6LkxzcC0OnPNu5yZqRUJ8lVOr/7bCPusN9zmziazWMxS9UGU1BtKStEwFgy0gj4HLyTFnCxlLZZMYgycNHNrsTOHGTieqc4+ji8E+GkVqs91Cm9pkWtaDonnb14xVTLk+wBS89P0gdFk1f3etstiE+LdM3jWyHL117jXgBZVPhS7Qo+9IGgexvpAABRF2ACeb+CxKwASeODSnI5eI/No48zSCmZcnhMmp6QHZ+ELxaKkvvJhEz2mB7lAvXrnDq3g3RYmuJiFNenzFuCu3NS6013Szf4Ar8czWc+w5ed/mCSeXufjwVmXRV145TWMAW6Z3SPpB/ltm0Bq3FQKqky4257kPjUdZkmVv4carhcNSPsHV7JBjBIY8fe/RcFJFPsy3Cio3TFG4HGoh8h00+XRPXYiGmMu2P/j3LJudcyoHB40RyG2+dpvU7g4ZuSVtubhQH7B4WJqD3daQXqyT5CjwJ7CH1k5+I=,iv:rrFYT3EDzp4SMzC+WreGL+58ZPxBj9TejrsgV6Clqt8=,tag:/Gdh3FC90K6wJk4DItQiKw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1yaq7q9cpuws7uay7z0x2frxwpmjlngk0vvqcg4mk9fzcxt09uusq95wfju
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQnpBUTU5Ujh0UkRTTjJ6
        ZmJUalVsNDFvV0d1ZjlBdUVnZXdQTncwbTF3CjBoRzZlVm5pMmM2cUpyOVVXbkQ3
        bFZ1ckJzZi9MV0VLOWNIWndaQWVNdHMKLS0tIGxDV0dsR3k3MG1pZlZJeCtuZENZ
        ZUhMSEk1Y1BYVzhzN0llOFFiNVV2V2sKtryVO6x+CNoVZk0B57mkJ8CWE7wYunzU
        o5T32Wpkv8gXR3+6gjwy0SawtXODKCYK/KJJWZIHmKeDmAZxqNrIPg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1lql6xv47pqyyakfrpdnw772pjf9mzvp0uh5mctkfwr75lzdjs3xs9tc68n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMXhqdGtXY2NIdEN6eDIz
        RDdkMGQrdmNvUytQWmFUeW55S2hWRFhKWWhzCis2ZC9SOWFYWFBzQUdzWnh4TGtX
        WnZBYlNNbk5QQ3hkVkl3ZzVJd1J2QkkKLS0tIFJKOHJ3MUE2ck0rbkNjeFRhbmNR
        M3NybExoMkU5TzBMTVFZU1FLYlJDeGcKX/WXhidcph9bAQlusSAUXlFNI9ivROhN
        EQXmP+Cw5wO1XanrQfuqTFcHWcwCHRbd/xEgCefiL7kfM84HyhD2Gw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1n70s2ssmssfd3x9wn4x39f7tuqvhnp7q6pluww54fq6swgq7au7s2d8gk6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdVhtaDBwakViZlhTUlls
        ZDBrY1RGVFk5emVWSUJMR3V2dEsrRituM24wCjFVT2F5Q2RWODBHU1FqSWMvTy9M
        UnVRZndKL2lYWkRwOHhCS1dpYXZjRVUKLS0tIEFxRjZoWDJQSWgxRU8vRFNWMXJm
        NTVtT0ZrQXBRUzZ4bDJ1aUFjaHZaOWcKf5J3u9ztSjoFtVnMwa9PD+yzcIl1yZgB
        OhGFVUQuJB6PbnRAfi71NxTUIZ/5DXPGlmqFW00QmT4b6ZRgGDve/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-07T20:48:34Z"
  mac: ENC[AES256_GCM,data:2+HGPCqWujmhZhd9uXIFuUhE/2fofMeXoMjFEmSWoSER61tUpvXdbqqiX23kxsE8YxVuINlSF09hGp8tQsK1UtFltF6WiwWqmBje8svF3NfbtLtUlj/InjunNfaOoCDQTXWf9ceEe9uqyRK00OlSRwDPJ+lST5vUGg5U6JK0z/0=,iv:UIQ+OOhhySuC3/yGJyzNcO5QLaH/hxoQBVgJRo+J1yM=,tag:fEqOwf4DrkXqVK1KoD/dCQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.4
