tailscale_auth_key: ENC[AES256_GCM,data:FD5po/mI5GxyQwekfYlzsRD4QpRMOfELRAmUaG5fpyCh8nO0XSpy42G3AiwslPzjXA5C4QxPH7CCzEih72w=,iv:UtP/SWjpH9FLLtfcIPO3x6NUO5Pl1oEqsJ6yHFoMlc0=,tag:AMPtnOuBGaXCSXxk+uUJeA==,type:str]
netdata_claim_token: ENC[AES256_GCM,data:D0gtg6CnIpis6xuHikMhFL71IxYBqzcgpELaXZ+O0AM8gxKi30qvZ5VW9YAl/hlJA71r4g4FIwmKOEk2E+eKov/BBy7/ZpnHAziVS1UzyZ87wcX8q0dweltkYvRMFQa/rhdnGKDiFcQyJ7f2UpD1uAqhRgHIIrHuBXk2TMAPj4kfQYP0+yDD,iv:JB+hLjFq9KHnBrcRWtnG6BFUu1Jt59/CHug1MPTqRK0=,tag:8sVIeUr22YcuBUP49NfnPQ==,type:str]
grafana_admin_password: ENC[AES256_GCM,data:eZ3DIyer7aKcJq1ybtA4EdXHOtSBvI8=,iv:eB8Gl1L47h0pNAUJyphQPukL5fxxWBJmqaXyYDJaAjk=,tag:mu/Vkra0Z/YOvx7qzIcCxQ==,type:str]
bazarr_api_key: ENC[AES256_GCM,data:o07CygB7UBak6efn8kniBp5TFpLtGkGxv0R9DR41V2Y=,iv:rPOEprOI8SKEk2qjWlYdf4KR1nYxGiq+tr16ndQyJ9w=,tag:N0JgWaMp2swK/kMDlLwgew==,type:str]
prowlarr_api_key: ENC[AES256_GCM,data:cC4XD+3Cxzok9RgjnSLaPUmKqhgLV+ySeXGS/c0bqVI=,iv:WP/REYRc2LNtUJVfAmsoU8l2TmeuHwnubEvRBfQY72s=,tag:JZdtUdPXvS7O9DXwHd1BcQ==,type:str]
radarr_api_key: ENC[AES256_GCM,data:lclbLdmltoJub+CPFt/kF+GO+N8O66buwEn4bTvhuYs=,iv:TVv2arnzod+cNz0sTyHfcsMnyE+QVuO5ZB/XFhs1gjU=,tag:mFBiKWaAwq7mX9eKQGTAbw==,type:str]
readarr_api_key: ENC[AES256_GCM,data:yuH6JY+2ZHVXuUkbrz1LHc7AhqV8v6VVS+i7KSwDfQc=,iv:XrRNbkD93jYsjIjflgmWf1Xbe3JpjlByBNh5e0IIMfU=,tag:82fsyEU5oRHrr8WiDJs6lA==,type:str]
sonarr_api_key: ENC[AES256_GCM,data:zHAaj9/4TEu+z94P9wn7MFPW0gAljiSm89phZqVNWzA=,iv:dRpeNXiJXZke1Qn/VKF5qhcUbAWklYegS3PuXOElROc=,tag:2kkAMKnUiklzpS1c9LlpaQ==,type:str]
lidarr_api_key: ENC[AES256_GCM,data:jsfH6/j002iUsRJhB/NxYDZnqjbNLBrsFxlQhUe08/U=,iv:5g6gFCs6ohVuLDLDZCqDgBu0sC5/lxxFSA0EHFbOYXg=,tag:7Ss6IjuRCI5I00CmDMcZ6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yaq7q9cpuws7uay7z0x2frxwpmjlngk0vvqcg4mk9fzcxt09uusq95wfju
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQnpBUTU5Ujh0UkRTTjJ6
            ZmJUalVsNDFvV0d1ZjlBdUVnZXdQTncwbTF3CjBoRzZlVm5pMmM2cUpyOVVXbkQ3
            bFZ1ckJzZi9MV0VLOWNIWndaQWVNdHMKLS0tIGxDV0dsR3k3MG1pZlZJeCtuZENZ
            ZUhMSEk1Y1BYVzhzN0llOFFiNVV2V2sKtryVO6x+CNoVZk0B57mkJ8CWE7wYunzU
            o5T32Wpkv8gXR3+6gjwy0SawtXODKCYK/KJJWZIHmKeDmAZxqNrIPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lql6xv47pqyyakfrpdnw772pjf9mzvp0uh5mctkfwr75lzdjs3xs9tc68n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMXhqdGtXY2NIdEN6eDIz
            RDdkMGQrdmNvUytQWmFUeW55S2hWRFhKWWhzCis2ZC9SOWFYWFBzQUdzWnh4TGtX
            WnZBYlNNbk5QQ3hkVkl3ZzVJd1J2QkkKLS0tIFJKOHJ3MUE2ck0rbkNjeFRhbmNR
            M3NybExoMkU5TzBMTVFZU1FLYlJDeGcKX/WXhidcph9bAQlusSAUXlFNI9ivROhN
            EQXmP+Cw5wO1XanrQfuqTFcHWcwCHRbd/xEgCefiL7kfM84HyhD2Gw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n70s2ssmssfd3x9wn4x39f7tuqvhnp7q6pluww54fq6swgq7au7s2d8gk6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdVhtaDBwakViZlhTUlls
            ZDBrY1RGVFk5emVWSUJMR3V2dEsrRituM24wCjFVT2F5Q2RWODBHU1FqSWMvTy9M
            UnVRZndKL2lYWkRwOHhCS1dpYXZjRVUKLS0tIEFxRjZoWDJQSWgxRU8vRFNWMXJm
            NTVtT0ZrQXBRUzZ4bDJ1aUFjaHZaOWcKf5J3u9ztSjoFtVnMwa9PD+yzcIl1yZgB
            OhGFVUQuJB6PbnRAfi71NxTUIZ/5DXPGlmqFW00QmT4b6ZRgGDve/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T20:37:48Z"
    mac: ENC[AES256_GCM,data:9peMYat03HVRHWI3ya+VVJ30y5KahAwnlMRHaKRCiBiO0A8u5Megbzd2MhhkGXJBjexDTQ/wTPhCR68OVzbLtTb9B0nJPtAljm+paq5a9FchoH1H6AG2OO7qcDrIU/57IKPcAjxo0RiLp5+3JlQkOKo2Iazw3YmTshtVNT/iZ50=,iv:aS4lh00n3n4fYSzlxvRxNptPH/+EJgSKQGDgzQQghtw=,tag:1zog29JVmZzg4uZB8HRN9g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
